const vm = require('node:vm');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const listeners = {}, viewListeners = {}, frames = [];
const canvas = { style: {}, width: 0, height: 0 };
const viewport = {height: 780, offsetTop: 0, addEventListener: (n,f) => viewListeners[n] = f};
const document = { activeElement: null, documentElement: {clientWidth: 390, style: {setProperty(){}}}, getElementById: id => id === 'canvas' ? canvas : null, addEventListener:(n,f)=>listeners[n]=f };
vm.runInNewContext(fs.readFileSync('web/viewport.js','utf8'), {window:{visualViewport:viewport,addEventListener(){}}, document, innerHeight:780, devicePixelRatio:3, requestAnimationFrame:f=>(frames.push(f),frames.length)});
const resize = height => {viewport.height=height;viewListeners.resize();while(frames.length)frames.shift()();};
assert.equal(canvas.height,2340);
document.activeElement={tagName:'INPUT'};listeners.focusin({target:document.activeElement});
resize(650);resize(440);resize(410);
assert.equal(canvas.height,2340,'Keyboard must not shrink Godot buffer');
assert.ok(parseFloat(canvas.style.top)<0,'Input is lifted above keyboard');
document.activeElement=null;listeners.focusout();while(frames.length)frames.shift()();
resize(540);assert.equal(canvas.height,2340,'Keep baseline during keyboard dismissal');
resize(780);assert.equal(canvas.style.top,'0px');assert.equal(canvas.height,2340);
resize(730);assert.equal(canvas.height,2190,'Normal browser chrome resize still works');
console.log('Viewport keyboard regression: PASS');
